baseurl      = "https://leteazer.github.io"
title        = "Teazer's Blog"
languageCode = "fr-FR"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Cybersecurity enthusiast"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/djahid-s/"

[[params.social]]
  name = "github"
  url = "https://github.com/LeTeazer"

[[params.social]]
  name = "hackthebox"
  url = "https://app.hackthebox.com/users/1317448"

[[params.social]]
  name = "tryhackme"
  url = "https://tryhackme.com/p/Teazer"


[languages]
  [languages.fr]
    title = "Teazer's Blog"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  [languages.fr.params]
    subtitle  = "Teazer's Blog"

    [languages.en.params.logo]
      logoText = "Teazer's Blog"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts"
